# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: challenge5
app: challenge5
org: lhidalgo

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  apiGateway:
    shouldStartNameWithService: true
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}-OrdersTable
  iam:
    role:
      statements:
        - Effect: Allow
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
          Action:      
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
        - Effect: Allow
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"
          Action:      
            - dynamodb:Query
            - dynamodb:Scan

functions:
  create:
    handler: functions/create_order.handler
    events:
      - http:
          path: /orders
          method: post
          cors: true
  list:
    handler: functions/list_order.handler
    events:
      - http:
          path: /orders
          method: get
          cors: true
  get:
    handler: functions/get_order.handler
    events:
      - http:
          path: /orders/{id}
          method: get
          cors: true

resources: 
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: coffeShopId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
          - IndexName: CoffeShopIdIndex
            KeySchema:
              - AttributeName: coffeShopId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        BillingMode: PAY_PER_REQUEST