# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: challenge5
app: challenge5
org: lhidalgo

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  apiGateway:
    shouldStartNameWithService: true
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}-OrdersTable
  iam:
    role:
      statements:
        # Basic IAM permissions
        - Effect: Allow
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
          Action:      
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
        
        # Permissions needed to query and scan the created indexes
        - Effect: Allow
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"
          Action:      
            - dynamodb:Query
            - dynamodb:Scan

functions:
  # API GateWay Handlers:
  # 
  # Order creation
  create:
    handler: functions/create_order.handler
    events:
      - http:
          path: /orders
          method: post
  # Orders fetching
  list:
    handler: functions/list_order.handler
    events:
      - http:
          path: /orders
          method: get
  # Fetch a specific order
  get:
    handler: functions/get_order.handler
    events:
      - http:
          path: /orders/{id}
          method: get
  # Update a specific order
  update:
    handler: functions/update_order.handler
    events:
      - http:
          path: /orders/{id}
          method: put
  # Delete a specific order
  delete:
    handler: functions/delete_order.handler
    events:
      - http:
          path: /orders/{id}
          method: delete

  # DynamoDB Stream Observer
  #
  # A handler has been added to listen and react to 
  # changes on the data base
  updateObserver:
    handler: functions/observe_order.handler
    events:
      # Unlike the other handlers, this function is
      # triggered by changes made to the dynamoDB table
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - OrdersTable
              - StreamArn
          batchSize: 100

resources: 
  Resources:
    # DynamoDB Table used by the Rest API
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # A new Table will be created for each environment
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: coffeShopId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        # `id` is used as primary key
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        # GSIs have been set up to list the items based on 
        # the user or coffee shop id.
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
          - IndexName: CoffeShopIdIndex
            KeySchema:
              - AttributeName: coffeShopId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST
        # A Stream is configured to trigger a lambda functions
        # New and Old images are return to enable the comparison
        # between the different versions
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES